### ISSUE TITLE
FR: Allow other password storage methods

### ISSUE THREAD

**Issue by phidauex** [IamTheCarl/system-mqtt#2]
The default password storage method relies on the system keychain, which for some reason does not work well on headless systems. Are there other ways that the password could be stored, or is there a way to ensure that the keychain will work with a headless system?

Error received:
```
$ system-mqtt set-password
Password: <entered interactively>
Fatal error: Keyring Error: Secret Service Error: Dbus error: "The name org.freedesktop.secrets was not provided by any .service files"
If you have not yet set the password run `system-mqtt set-password`.
```

**Comment by IamTheCarl** [comment]
I have a requirement that passwords not be stored in plain-text form, so I try to pass it off to OS utilities and hope they can pull in a TPM or some other encrypted storage method. This was just a method recommended by a guy in the Rust Discord.

If you can think of a secure way to store a password that works well in your environment, I'm willing to listen.

**Comment by phidauex** [comment]
Totally agreed on not storing in plaintext. I'll think about it and see if I can come up with any secure alternative methods.

**Comment by Asiak3** [comment]
hi! have you found any solution for this? thx for your work!

**Comment by IamTheCarl** [comment]
An experemental version of this feature has been implemented into the [dev](https://github.com/IamTheCarl/system-mqtt/tree/dev) branch.

This approach copies how ssh and OpenGPG handle this kind of situation. I consider it less secure than the system keyring but I think it's been pretty well proven that a system keyring is not always available.

**Comment by phidauex** [comment]
Thanks for the update, I'll update my fork and test when I have some time!
